#! /bin/sh

## Config file created by Pentacloud, 11/06/22

##------ Bspwm ------##

# Window settings and workspaces
bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap           4
bspc config split_ratio          0.50

bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle 	 	false
bspc config paddingless_monocle  	true
bspc config focus_follows_pointer	false

bspc config focused_border_color	"#ff0000"
bspc config normal_border_color         "#000000"

##------- Workspaces ------##

# Kill all existing rules first
bspc rule -r *:*

# Workspace 1 > Terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on

# Workspace 2 > Internet browser
bspc rule -a firefox desktop='^2' follow=on focus=on

# Workspace 3 > File manager, torrent client, etc.
bspc rule -a Nemo desktop='^3' follow=on focus=on
bspc rule -a qBittorent desktop='^3' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^3' follow=on focus=on
bspc rule -a Xarchiver desktop='^3' follow=on focus=on
bspc rule -a Thunar desktop='^3' follow=on focus=on

# Workspace 4 > Media
bspc rule -a obs desktop='^4' state=floating follow=on focus=on
bspc rule -a mpv desktop='^4' follow=on focus=on
bspc rule -a Viewnior desktop='^4' follow=on focus=on

# Workspace 5 > Settings and configurations
bspc rule -a Lxappearance desktop='^5' follow=on focus=on
bspc rule -a Gparted desktop='^5' follow=on focus=on
bspc rule -a Nitrogen desktop='^5' follow=on focus=on
bspc rule -a Xfce4-power-manager-settings desktop='^5' follow=on focus=on
bspc rule -a Pavucontrol desktop='^5' follow=on focus=on

# Workspace 6 > Communications
bspc rule -a discord desktop='^6' follow=on focus=on
bspc rule -a Hexchat desktop='^6' follow=on focus=on
bspc rule -a Thunderbird desktop='^6' follow=on focus=on

##------ Essential startup apps ------## 

# Kill existing apps before restarting bspwm
killall -9 sxhkd dunst ksuperkey xfce4-power-manager &

# Launch policy kit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Enable Super Keys as menu key
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Launch compositor (picom-jonaburg)
picom --config ~/.config/bspwm/picom.conf --experimental-backends &

# Start polybar
bash ~/.config/polybar/shades/launch.sh &

# Launch power manager (battery level and optimizations)
xfce4-power-manager &

# Launch notification daemon
dunst -conf ~/.config/bspwm/dunstrc &

# Fix cursors in WM
xsetroot -cursor_name left_ptr &

# Restore wallpaper
nitrogen --restore &

# Set default sink (for seamless wireless headphone connection and output)
sh ~/.config/bspwm/wireless-headphone.sh &

##------ EOF ------##
